version: '2'
services:
  mysql:
    build: ./docker-configs/mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: admin
    volumes:
      - ./data/mysql:/var/lib/mysql
      - ./data/init.d:/docker-entrypoint-initdb.d
  php56-apache:
    build: ./docker-configs/php56-apache
    volumes:
      - ./php56-apps:/var/www/html
      - ./docker-configs/php56-apache/000-default.conf:/etc/apache2/sites-available/000-default.conf
    depends_on:
      - mysql
    links:
      - mysql
    environment:
      - VIRTUAL_HOST=blog.laravel.local
  nginx-proxy:
    image: jwilder/nginx-proxy
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - /etc/localtime:/etc/localtime:ro
      - ./docker-configs/nginx-proxy/certs:/etc/nginx/certs
    ports:
      - '80:80'
      - '443:443'
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=mysql
      - PMA_USER=root
      - PMA_PASSWORD=admin
      - VIRTUAL_HOST=phpmyadmin.local
    ports:
      - 8085:80
    links:
      - mysql
  php7-apache:
    build: ./docker-configs/php7-apache
    volumes:
      - ./php7-apache:/var/www/html
      - ./docker-configs/php7-apache/000-default.conf:/etc/apache2/sites-available/000-default.conf
    depends_on:
      - mysql
    links:
      - mysql
    environment:
      - VIRTUAL_HOST=laravel5-1.local
